AWSTemplateFormatVersion: "2010-09-09"
Description: GitHub Actions OIDC Provider and IAM Role for CI/CD deployment.

Parameters:
  ProjectName:
    Type: String
    Default: successfulsuccess
    Description: Prefix for resource names.

  GitHubRepo:
    Type: String
    Default: OlenaPasiura/SuccessfulSuccess_spry
    Description: GitHub organization/username and repository name (e.g. OlenaPasiura/SuccessfulSuccess_spry).

Resources:
  GithubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c5876025b5421a75037d450730604c4c6ecb799
      Tags:
        - Key: PROJECT_NAME
          Value: !Ref ProjectName

  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-github-actions-role"
      Description: IAM Role assumed by GitHub Actions via OIDC
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref GithubOidcProvider
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": "sts.amazonaws.com"
              StringLike:
                "token.actions.githubusercontent.com:sub":
                  - !Sub "repo:${GitHubRepo}:*"
                  - "repo:OlenaPasiura*/SuccessfulSuccess_spry*:*"
                  - "repo:OlenaPasiura@244303299/SuccessfulSuccess_spry@1399715498:*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
      Policies:
        - PolicyName: ECSDeployPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeTaskDefinition
                  - ecs:RegisterTaskDefinition
                  - ecs:DescribeServices
                  - ecs:UpdateService
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
      Tags:
        - Key: PROJECT_NAME
          Value: !Ref ProjectName

Outputs:
  RoleArn:
    Description: ARN of the IAM role to assume in GitHub Actions
    Value: !GetAtt GitHubActionsRole.Arn
  OidcProviderArn:
    Description: ARN of the GitHub OIDC provider
    Value: !Ref GithubOidcProvider
